apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: test-set3
spec:
  providers:
    - name: gcp-1
      providerType: gcp
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.11
        path: "templates/terraformer/gcp"
      secretRef:
        name: gcp-secret
        namespace: e2e-secrets
    - name: hetzner-1
      providerType: hetzner
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.11
        path: "templates/terraformer/hetzner"
      secretRef:
        name: hetzner-secret
        namespace: e2e-secrets
  nodePools:
    dynamic:
      - name: htz-cmpt-nodes
        providerSpec:
          name: hetzner-1
          region: nbg1
          zone: nbg1-dc3
        count: 1
        serverType: cpx11
        image: ubuntu-24.04
        storageDiskSize: 50

      - name: gcp-cmpt-nodes
        providerSpec:
          name: gcp-1
          region: europe-west1
          zone: europe-west1-b
        count: 1
        serverType: e2-small
        image: ubuntu-2404-noble-amd64-v20250313
        storageDiskSize: 50

  kubernetes:
    clusters:
      - name: ts3-c-1-cluster-test-set-no3
        version: 1.30.0
        network: 192.168.2.0/24
        pools:
          control:
            - htz-cmpt-nodes
          compute:
            - htz-cmpt-nodes
            - gcp-cmpt-nodes
