apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: test-set3
spec:
  providers:
    - name: gcp-1
      providerType: gcp
      secretRef:
        name: gcp-secret
        namespace: e2e-secrets
    - name: hetzner-1
      providerType: hetzner
      secretRef:
        name: hetzner-secret
        namespace: e2e-secrets
    - name: cloudflare-1
      providerType: cloudflare
      secretRef:
        name: cloudflare-secret
        namespace: e2e-secrets
  nodePools:
    dynamic:
      - name: htz-cmpt-nodes
        providerSpec:
          name: hetzner-1
          region: nbg1
          zone: nbg1-dc3
        count: 1
        serverType: cpx11
        image: ubuntu-24.04
        storageDiskSize: 50

      #-----------LB nodepools----------
      - name: gcp-ldbl-nodes
        providerSpec:
          name: gcp-1
          region: europe-west1
          zone: europe-west1-c
        count: 1
        serverType: e2-small
        image: ubuntu-minimal-2404-noble-amd64-v20241116
        storageDiskSize: 50

  kubernetes:
    clusters:
      - name: ts3-c-1-cluster-test-set-no3
        version: 1.29.0
        network: 192.168.2.0/24
        pools:
          control:
            - htz-cmpt-nodes
          compute:
            - htz-cmpt-nodes
  loadBalancers:
    roles:
      - name: random-lb
        protocol: tcp
        port: 6440
        targetPort: 6440
        targetPools:
          - htz-cmpt-nodes
    clusters:
      - name: ts3-lb1-cluster-test-set-no3
        roles:
          - random-lb
        dns:
          dnsZone: claudie.dev
          provider: cloudflare-1
        targetedK8s: ts3-c-1-cluster-test-set-no3
        pools:
          - gcp-ldbl-nodes
