apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: succeeds-on-last-3
spec:
  providers:
    - name: azure-sponsor-1
      providerType: azure
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.8
        path: "templates/terraformer/azure"
      secretRef:
        name: azure-sponsorship-secret
        namespace: e2e-secrets
    - name: hetznerdns-1
      providerType: hetznerdns
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.8
        path: "templates/terraformer/hetznerdns"
      secretRef:
        name: hetznerdns-secret
        namespace: e2e-secrets
  nodePools:
    dynamic:
      - name: azr-nodes
        providerSpec:
          name: azure-sponsor-1
          region: Germany West Central
          zone: "3"
        count: 1
        serverType: Standard_B2s
        image: Canonical:ubuntu-24_04-lts:server:24.04.202502210
        storageDiskSize: 50
  kubernetes:
    clusters:
      - name: succeeds-on-last-3-cluster-0
        version: 1.30.0
        network: 192.168.2.0/24
        pools:
          control:
            - azr-nodes
          compute:
            - azr-nodes
  loadBalancers:
    roles:
      - name: apiserver-lb-hetzner
        protocol: tcp
        port: 6443
        targetPort: 6443
        targetPools:
          - azr-nodes
    clusters:
      - name: succeeds-on-last-3-lbcluster
        roles:
          - apiserver-lb-hetzner
        dns:
          dnsZone: claudie.dev
          provider: hetznerdns-1
        targetedK8s: succeeds-on-last-3-cluster-0
        pools:
          - azr-nodes
