apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: rolling-update
spec:
  providers:
    - name: hetzner-1
      providerType: hetzner
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: "v0.9.1"
        path: "templates/terraformer/hetzner"
      secretRef:
        name: hetzner-secret
        namespace: e2e-secrets
    - name: oci-1
      providerType: oci
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: "v0.9.1"
        path: "templates/terraformer/oci"
      secretRef:
        name: oci-secret
        namespace: e2e-secrets
    - name: aws-1
      providerType: aws
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: "v0.9.1"
        path: "templates/terraformer/aws"
      secretRef:
        name: aws-secret
        namespace: e2e-secrets
    - name: azure-payed-1
      providerType: azure
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: "v0.9.1"
        path: "templates/terraformer/azure"
      secretRef:
        name: azure-secret
        namespace: e2e-secrets
    - name: azure-sponsor-2
      providerType: azure
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: "v0.9.1"
        path: "templates/terraformer/azure"
      secretRef:
        name: azure-sponsorship-secret
        namespace: e2e-secrets
  nodePools:
    static:
      - name: static-pool-01
        nodes:
          - endpoint: replace-me
            secretRef:
              name: static-nodes-key
              namespace: e2e-secrets
    dynamic:
      - name: oci-ldbl-nodes
        providerSpec:
          name: oci-1
          region: eu-frankfurt-1
          zone: hsVQ:EU-FRANKFURT-1-AD-2
        count: 1
        serverType: VM.Standard2.1
        # ubuntu minimal
        # https://docs.oracle.com/en-us/iaas/images/ubuntu-2404/canonical-ubuntu-24-04-2024-08-28-0.htm
        image: ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa7hxwyz4qiasffo7n7s4ep5lywpzwgkc2am65frqrqinoyitmxxla
        storageDiskSize: 50

      - name: azr-ctrl-nodes
        providerSpec:
          name: azure-sponsor-2
          region: Germany West Central
          zone: "1"
        count: 2
        serverType: Standard_B2s
        image: Canonical:ubuntu-24_04-lts:server:latest
        labels:
          test-set: rolling-update-test
        annotations:
          claudie.io/example-annotation: >
            ["rolling-update-test"]

      - name: htz-cmpt-nodes
        providerSpec:
          name: hetzner-1
          region: nbg1
          zone: nbg1-dc3
        count: 1
        serverType: cpx11
        image: ubuntu-24.04
        storageDiskSize: 50

  kubernetes:
    clusters:
      - name: ts-rolling-update-nodepools1
        version: 1.30.0
        network: 192.168.2.0/24
        pools:
          control:
            - static-pool-01
          compute:
            - azr-ctrl-nodes
  loadBalancers:
    roles:
      - name: port1
        protocol: tcp
        port: 6443
        targetPort: 6443
        targetPools:
          - static-pool-01
      - name: port2
        protocol: tcp
        port: 6448
        targetPort: 6448
        targetPools:
          - azr-ctrl-nodes
    clusters:
      - name: ts-rolling-update-lbpools001
        roles:
          - port1
        dns:
          dnsZone: aws.e2e.claudie.io
          provider: aws-1
        targetedK8s: ts-rolling-update-nodepools1
        pools:
          - oci-ldbl-nodes
      - name: ts-rolling-update-lbpools002
        roles:
          - port2
        dns:
          dnsZone: azure.e2e.claudie.io
          provider: azure-payed-1
        targetedK8s: ts-rolling-update-nodepools1
        pools:
          - htz-cmpt-nodes
