apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: proxy-without-hetzner
spec:
  providers:
    - name: gcp-1
      providerType: gcp
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.14
        path: "templates/terraformer/gcp"
      secretRef:
        name: gcp-secret
        namespace: e2e-secrets
  nodePools:
    dynamic:
      - name: gcp-ctrl-nodes
        providerSpec:
          name: gcp-1
          region: europe-west2
          zone: europe-west2-c
        count: 1
        serverType: e2-medium
        image: ubuntu-2404-noble-amd64-v20250313
        labels:
          test-set: proxy-without-hetzner
        annotations:
          claudie.io/example-annotation: >
            ["proxy-without-hetzner"]
      - name: gcp-cmpt-nodes
        providerSpec:
          name: gcp-1
          region: europe-west1
          zone: europe-west1-b
        count: 2
        serverType: e2-small
        image: ubuntu-2404-noble-amd64-v20250313
        storageDiskSize: 50
        labels:
          test-set: proxy-without-hetzner
        annotations:
          claudie.io/example-annotation: >
            ["proxy-without-hetzner"]
  kubernetes:
    clusters:
      - name: proxy-without-hetzner
        version: "1.30.0"
        network: 192.168.2.0/24
        installationProxy:
          mode: "default"
          endpoint: http://proxy.claudie.io:8880
        pools:
          control:
            - gcp-ctrl-nodes
          compute:
            - gcp-cmpt-nodes
