apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: succeeds-on-last-1
spec:
  providers:
    - name: aws-1
      providerType: aws
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.8
        path: "templates/terraformer/aws"
      secretRef:
        name: aws-secret
        namespace: e2e-secrets
  nodePools:
    dynamic:
      - name: aws-cmpt-00002
        providerSpec:
          name: aws-1
          region: eu-west-3
          zone: eu-west-3a
        count: 1
        serverType: t3.small
        #ubuntu
        image: ami-045a8ab02aadf4f88
        storageDiskSize: 50
  kubernetes:
    clusters:
      - name: succeeds-on-last-1-cluster-0
        version: 1.30.0
        network: 192.168.2.0/24
        pools:
          control:
            - aws-cmpt-00002
          compute:
            - aws-cmpt-00002
