---
- hosts: all
  gather_facts: no
  become: yes
  vars:
    nofile_soft: 65535
    nofile_hard: 65535
    file_max: 2097152
  # Install longhorn  dependencies
  tasks:
    - name: install open-iscsi
      ansible.builtin.apt:
        name: open-iscsi
        state: present
        update_cache: true

    - name: install nfs-common
      ansible.builtin.apt:
        name: nfs-common
        state: present
        update_cache: true

    - name: Update /etc/multipath.conf with blacklist configuration
      blockinfile:
        path: /etc/multipath.conf
        block: |
          blacklist {
              devnode "^sd[a-z0-9]+"
              devnode "^vd[a-z0-9]+"
              devnode "^nvme[a-z0-9]+"
          }
        create: yes

    - name: Restart multipathd.service
      ansible.builtin.systemd:
        name: multipathd.service
        state: restarted
      # some cloud providers may not use the multipathd service
      # thus make the error not fatal.
      ignore_errors: yes

      # Update node limits.
    - name: Modify limits.conf
      blockinfile:
        path: /etc/security/limits.conf
        block: |
          * soft nofile {{ nofile_soft }}
          * hard nofile {{ nofile_hard }}
          root soft nofile {{ nofile_soft }}
          root hard nofile {{ nofile_hard }}
        state: present

    - name: Ensure PAM limits are enabled
      lineinfile:
        path: /etc/pam.d/common-session
        line: "session required pam_limits.so"
        state: present

    - name: Ensure PAM limits are enabled for non-interactive sessions
      lineinfile:
        path: /etc/pam.d/common-session-noninteractive
        line: "session required pam_limits.so"
        state: present

    - name: Configure systemd system limits
      ansible.builtin.lineinfile:
        path: /etc/systemd/system.conf
        regexp: "^#?DefaultLimitNOFILE="
        line: "DefaultLimitNOFILE={{ nofile_hard }}"

    - name: Configure systemd user limits
      ansible.builtin.lineinfile:
        path: /etc/systemd/user.conf
        regexp: "^#?DefaultLimitNOFILE="
        line: "DefaultLimitNOFILE={{ nofile_hard }}"

    - name: Reload systemd configuration
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Set kernel file handle maximum
      ansible.builtin.sysctl:
        name: fs.file-max
        value: "{{ file_max }}"
        state: present
        reload: yes
