---
- hosts: all
  gather_facts: no
  become: yes
  # Install longhorn  dependencies
  tasks:
    - name: install open-iscsi
      ansible.builtin.apt:
        name: open-iscsi
        state: present
        update_cache: true

    - name: install nfs-common
      ansible.builtin.apt:
        name: nfs-common
        state: present
        update_cache: true

    - name: Update /etc/multipath.conf with blacklist configuration
      blockinfile:
        path: /etc/multipath.conf
        block: |
          blacklist {
              devnode "^sd[a-z0-9]+"
              devnode "^vd[a-z0-9]+"
              devnode "^nvme[a-z0-9]+"
          }
        create: yes

    - name: Restart multipathd.service
      ansible.builtin.systemd:
        name: multipathd.service
        state: restarted
      # some cloud providers may not use the multipathd service
      # thus make the error not fatal.
      ignore_errors: yes
