---
- name: Install Wireguard and dependencies
  ansible.builtin.apt:
    pkg:
      - wireguard
      - net-tools
    state: present
    update_cache: true
  retries: 2
  delay: 10
  register: res
  until: res is not failed
  # wireguard packages are few hundred Kibs in size
  # having a timeout of 8 mins with 2 retries is generous.
  async: 480
  poll: 5
