apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: claudie-operator-role
  labels:
    app.kubernetes.io/part-of: claudie
    app.kubernetes.io/name: claudie-operator
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources: ["events"]
    verbs:
      - create
      - list
      - watch
      - patch
  - apiGroups: ["claudie.io"]
    resources: ["inputmanifests", "settings"]
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["claudie.io"]
    resources: ["inputmanifests/finalizers"]
    verbs:
      - update
  - apiGroups: ["claudie.io"]
    resources: ["inputmanifests/status"]
    verbs:
      - get
      - patch
      - update
