apiVersion: apps/v1
kind: Deployment
metadata:
  name: builder
  labels:
    app.kubernetes.io/part-of: claudie
    app.kubernetes.io/name: builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: claudie
      app.kubernetes.io/name: builder
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: claudie
        app.kubernetes.io/name: builder
    spec:
      terminationGracePeriodSeconds: 5400
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: builder
          imagePullPolicy: Always
          image: ghcr.io/berops/claudie/builder
          resources:
            requests:
              cpu: 20m
              memory: 20Mi
            limits:
              memory: 65Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
          env:
            - name: MANAGER_PORT
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: MANAGER_PORT
            - name: MANAGER_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: MANAGER_HOSTNAME
            - name: TERRAFORMER_PORT
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: TERRAFORMER_PORT
            - name: TERRAFORMER_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: TERRAFORMER_HOSTNAME
            - name: ANSIBLER_PORT
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: ANSIBLER_PORT
            - name: ANSIBLER_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: ANSIBLER_HOSTNAME
            - name: KUBE_ELEVEN_PORT
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: KUBE_ELEVEN_PORT
            - name: KUBE_ELEVEN_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: KUBE_ELEVEN_HOSTNAME
            - name: KUBER_PORT
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: KUBER_PORT
            - name: KUBER_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: KUBER_HOSTNAME
            - name: GOLANG_LOG
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: GOLANG_LOG
          ports:
            - name: "metrics"
              containerPort: 9090
          readinessProbe:
            httpGet:
              path: /health
              port: 50051
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 50051
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 3
            periodSeconds: 30
