apiVersion: claudie.io/v1beta1
kind: TemplateGitReference
metadata:
  name: default-claudie-templates
spec:
  endpoint:
    url: github.com/berops/claudie-config
    protocol: https
  commit: replace-me
  paths:
    terraformer: templates/terraformer
    playbooks: templates/playbooks
    config-lb: templates/config-lb
    config-k8s: templates/config-k8s
    manifests-k8s: templates/manifests-k8s
