// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: proto/frontend.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendAutoscalerEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputManifestName      string `protobuf:"bytes,1,opt,name=InputManifestName,proto3" json:"InputManifestName,omitempty"`
	InputManifestNamespace string `protobuf:"bytes,2,opt,name=InputManifestNamespace,proto3" json:"InputManifestNamespace,omitempty"`
}

func (x *SendAutoscalerEventRequest) Reset() {
	*x = SendAutoscalerEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_frontend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendAutoscalerEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAutoscalerEventRequest) ProtoMessage() {}

func (x *SendAutoscalerEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frontend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAutoscalerEventRequest.ProtoReflect.Descriptor instead.
func (*SendAutoscalerEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_frontend_proto_rawDescGZIP(), []int{0}
}

func (x *SendAutoscalerEventRequest) GetInputManifestName() string {
	if x != nil {
		return x.InputManifestName
	}
	return ""
}

func (x *SendAutoscalerEventRequest) GetInputManifestNamespace() string {
	if x != nil {
		return x.InputManifestNamespace
	}
	return ""
}

type SendAutoscalerEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendAutoscalerEventResponse) Reset() {
	*x = SendAutoscalerEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_frontend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendAutoscalerEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAutoscalerEventResponse) ProtoMessage() {}

func (x *SendAutoscalerEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_frontend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAutoscalerEventResponse.ProtoReflect.Descriptor instead.
func (*SendAutoscalerEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_frontend_proto_rawDescGZIP(), []int{1}
}

var File_proto_frontend_proto protoreflect.FileDescriptor

var file_proto_frontend_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x22,
	0x82, 0x01, 0x0a, 0x1a, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c,
	0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c,
	0x0a, 0x11, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x16,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x22, 0x1d, 0x0a, 0x1b, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x6f,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x73, 0x0a, 0x0f, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x75,
	0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x23, 0x2e,
	0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x6f,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x41, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_frontend_proto_rawDescOnce sync.Once
	file_proto_frontend_proto_rawDescData = file_proto_frontend_proto_rawDesc
)

func file_proto_frontend_proto_rawDescGZIP() []byte {
	file_proto_frontend_proto_rawDescOnce.Do(func() {
		file_proto_frontend_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_frontend_proto_rawDescData)
	})
	return file_proto_frontend_proto_rawDescData
}

var file_proto_frontend_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_frontend_proto_goTypes = []interface{}{
	(*SendAutoscalerEventRequest)(nil),  // 0: claudie.SendAutoscalerEventRequest
	(*SendAutoscalerEventResponse)(nil), // 1: claudie.SendAutoscalerEventResponse
}
var file_proto_frontend_proto_depIdxs = []int32{
	0, // 0: claudie.FrontendService.SendAutoscalerEvent:input_type -> claudie.SendAutoscalerEventRequest
	1, // 1: claudie.FrontendService.SendAutoscalerEvent:output_type -> claudie.SendAutoscalerEventResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_frontend_proto_init() }
func file_proto_frontend_proto_init() {
	if File_proto_frontend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_frontend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendAutoscalerEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_frontend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendAutoscalerEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_frontend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_frontend_proto_goTypes,
		DependencyIndexes: file_proto_frontend_proto_depIdxs,
		MessageInfos:      file_proto_frontend_proto_msgTypes,
	}.Build()
	File_proto_frontend_proto = out.File
	file_proto_frontend_proto_rawDesc = nil
	file_proto_frontend_proto_goTypes = nil
	file_proto_frontend_proto_depIdxs = nil
}
