// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: proto/kuber.proto

package pb

import (
	spec "github.com/berops/claudie/proto/pb/spec"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetUpStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DesiredCluster *spec.K8Scluster `protobuf:"bytes,1,opt,name=desiredCluster,proto3" json:"desiredCluster,omitempty"`
}

func (x *SetUpStorageRequest) Reset() {
	*x = SetUpStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUpStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUpStorageRequest) ProtoMessage() {}

func (x *SetUpStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUpStorageRequest.ProtoReflect.Descriptor instead.
func (*SetUpStorageRequest) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{0}
}

func (x *SetUpStorageRequest) GetDesiredCluster() *spec.K8Scluster {
	if x != nil {
		return x.DesiredCluster
	}
	return nil
}

type SetUpStorageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DesiredCluster *spec.K8Scluster `protobuf:"bytes,1,opt,name=desiredCluster,proto3" json:"desiredCluster,omitempty"`
}

func (x *SetUpStorageResponse) Reset() {
	*x = SetUpStorageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUpStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUpStorageResponse) ProtoMessage() {}

func (x *SetUpStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUpStorageResponse.ProtoReflect.Descriptor instead.
func (*SetUpStorageResponse) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{1}
}

func (x *SetUpStorageResponse) GetDesiredCluster() *spec.K8Scluster {
	if x != nil {
		return x.DesiredCluster
	}
	return nil
}

type StoreKubeconfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cluster     *spec.K8Scluster `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	ProjectName string           `protobuf:"bytes,2,opt,name=projectName,proto3" json:"projectName,omitempty"`
}

func (x *StoreKubeconfigRequest) Reset() {
	*x = StoreKubeconfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreKubeconfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreKubeconfigRequest) ProtoMessage() {}

func (x *StoreKubeconfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreKubeconfigRequest.ProtoReflect.Descriptor instead.
func (*StoreKubeconfigRequest) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{2}
}

func (x *StoreKubeconfigRequest) GetCluster() *spec.K8Scluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *StoreKubeconfigRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

type StoreKubeconfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StoreKubeconfigResponse) Reset() {
	*x = StoreKubeconfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreKubeconfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreKubeconfigResponse) ProtoMessage() {}

func (x *StoreKubeconfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreKubeconfigResponse.ProtoReflect.Descriptor instead.
func (*StoreKubeconfigResponse) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{3}
}

type DeleteKubeconfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cluster *spec.K8Scluster `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
}

func (x *DeleteKubeconfigRequest) Reset() {
	*x = DeleteKubeconfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKubeconfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKubeconfigRequest) ProtoMessage() {}

func (x *DeleteKubeconfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKubeconfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteKubeconfigRequest) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteKubeconfigRequest) GetCluster() *spec.K8Scluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type DeleteKubeconfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteKubeconfigResponse) Reset() {
	*x = DeleteKubeconfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKubeconfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKubeconfigResponse) ProtoMessage() {}

func (x *DeleteKubeconfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKubeconfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteKubeconfigResponse) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{5}
}

type DeleteNodesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cluster     *spec.K8Scluster `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	WorkerNodes []string         `protobuf:"bytes,2,rep,name=workerNodes,proto3" json:"workerNodes,omitempty"`
	MasterNodes []string         `protobuf:"bytes,3,rep,name=masterNodes,proto3" json:"masterNodes,omitempty"`
}

func (x *DeleteNodesRequest) Reset() {
	*x = DeleteNodesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodesRequest) ProtoMessage() {}

func (x *DeleteNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodesRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodesRequest) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteNodesRequest) GetCluster() *spec.K8Scluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *DeleteNodesRequest) GetWorkerNodes() []string {
	if x != nil {
		return x.WorkerNodes
	}
	return nil
}

func (x *DeleteNodesRequest) GetMasterNodes() []string {
	if x != nil {
		return x.MasterNodes
	}
	return nil
}

type DeleteNodesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cluster *spec.K8Scluster `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
}

func (x *DeleteNodesResponse) Reset() {
	*x = DeleteNodesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodesResponse) ProtoMessage() {}

func (x *DeleteNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodesResponse.ProtoReflect.Descriptor instead.
func (*DeleteNodesResponse) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteNodesResponse) GetCluster() *spec.K8Scluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type StoreClusterMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cluster       *spec.K8Scluster  `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	ProjectName   string            `protobuf:"bytes,2,opt,name=projectName,proto3" json:"projectName,omitempty"`
	Loadbalancers []*spec.LBcluster `protobuf:"bytes,3,rep,name=loadbalancers,proto3" json:"loadbalancers,omitempty"`
}

func (x *StoreClusterMetadataRequest) Reset() {
	*x = StoreClusterMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreClusterMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreClusterMetadataRequest) ProtoMessage() {}

func (x *StoreClusterMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreClusterMetadataRequest.ProtoReflect.Descriptor instead.
func (*StoreClusterMetadataRequest) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{8}
}

func (x *StoreClusterMetadataRequest) GetCluster() *spec.K8Scluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *StoreClusterMetadataRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *StoreClusterMetadataRequest) GetLoadbalancers() []*spec.LBcluster {
	if x != nil {
		return x.Loadbalancers
	}
	return nil
}

type StoreClusterMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StoreClusterMetadataResponse) Reset() {
	*x = StoreClusterMetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreClusterMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreClusterMetadataResponse) ProtoMessage() {}

func (x *StoreClusterMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreClusterMetadataResponse.ProtoReflect.Descriptor instead.
func (*StoreClusterMetadataResponse) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{9}
}

type StoreLBScrapeConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cluster              *spec.K8Scluster  `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	DesiredLoadbalancers []*spec.LBcluster `protobuf:"bytes,2,rep,name=desiredLoadbalancers,proto3" json:"desiredLoadbalancers,omitempty"`
}

func (x *StoreLBScrapeConfigRequest) Reset() {
	*x = StoreLBScrapeConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreLBScrapeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreLBScrapeConfigRequest) ProtoMessage() {}

func (x *StoreLBScrapeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreLBScrapeConfigRequest.ProtoReflect.Descriptor instead.
func (*StoreLBScrapeConfigRequest) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{10}
}

func (x *StoreLBScrapeConfigRequest) GetCluster() *spec.K8Scluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *StoreLBScrapeConfigRequest) GetDesiredLoadbalancers() []*spec.LBcluster {
	if x != nil {
		return x.DesiredLoadbalancers
	}
	return nil
}

type StoreLBScrapeConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StoreLBScrapeConfigResponse) Reset() {
	*x = StoreLBScrapeConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreLBScrapeConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreLBScrapeConfigResponse) ProtoMessage() {}

func (x *StoreLBScrapeConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreLBScrapeConfigResponse.ProtoReflect.Descriptor instead.
func (*StoreLBScrapeConfigResponse) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{11}
}

type RemoveLBScrapeConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cluster *spec.K8Scluster `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
}

func (x *RemoveLBScrapeConfigRequest) Reset() {
	*x = RemoveLBScrapeConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveLBScrapeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveLBScrapeConfigRequest) ProtoMessage() {}

func (x *RemoveLBScrapeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveLBScrapeConfigRequest.ProtoReflect.Descriptor instead.
func (*RemoveLBScrapeConfigRequest) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveLBScrapeConfigRequest) GetCluster() *spec.K8Scluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type RemoveLBScrapeConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveLBScrapeConfigResponse) Reset() {
	*x = RemoveLBScrapeConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveLBScrapeConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveLBScrapeConfigResponse) ProtoMessage() {}

func (x *RemoveLBScrapeConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveLBScrapeConfigResponse.ProtoReflect.Descriptor instead.
func (*RemoveLBScrapeConfigResponse) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{13}
}

type DeleteClusterMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cluster *spec.K8Scluster `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
}

func (x *DeleteClusterMetadataRequest) Reset() {
	*x = DeleteClusterMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteClusterMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClusterMetadataRequest) ProtoMessage() {}

func (x *DeleteClusterMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClusterMetadataRequest.ProtoReflect.Descriptor instead.
func (*DeleteClusterMetadataRequest) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteClusterMetadataRequest) GetCluster() *spec.K8Scluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type DeleteClusterMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteClusterMetadataResponse) Reset() {
	*x = DeleteClusterMetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteClusterMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClusterMetadataResponse) ProtoMessage() {}

func (x *DeleteClusterMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClusterMetadataResponse.ProtoReflect.Descriptor instead.
func (*DeleteClusterMetadataResponse) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{15}
}

type PatchNodesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cluster *spec.K8Scluster `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
}

func (x *PatchNodesRequest) Reset() {
	*x = PatchNodesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchNodesRequest) ProtoMessage() {}

func (x *PatchNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchNodesRequest.ProtoReflect.Descriptor instead.
func (*PatchNodesRequest) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{16}
}

func (x *PatchNodesRequest) GetCluster() *spec.K8Scluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type PatchNodesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PatchNodesResponse) Reset() {
	*x = PatchNodesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchNodesResponse) ProtoMessage() {}

func (x *PatchNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchNodesResponse.ProtoReflect.Descriptor instead.
func (*PatchNodesResponse) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{17}
}

type SetUpClusterAutoscalerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectName string           `protobuf:"bytes,1,opt,name=projectName,proto3" json:"projectName,omitempty"`
	Cluster     *spec.K8Scluster `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
}

func (x *SetUpClusterAutoscalerRequest) Reset() {
	*x = SetUpClusterAutoscalerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUpClusterAutoscalerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUpClusterAutoscalerRequest) ProtoMessage() {}

func (x *SetUpClusterAutoscalerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUpClusterAutoscalerRequest.ProtoReflect.Descriptor instead.
func (*SetUpClusterAutoscalerRequest) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{18}
}

func (x *SetUpClusterAutoscalerRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *SetUpClusterAutoscalerRequest) GetCluster() *spec.K8Scluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type SetUpClusterAutoscalerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetUpClusterAutoscalerResponse) Reset() {
	*x = SetUpClusterAutoscalerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUpClusterAutoscalerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUpClusterAutoscalerResponse) ProtoMessage() {}

func (x *SetUpClusterAutoscalerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUpClusterAutoscalerResponse.ProtoReflect.Descriptor instead.
func (*SetUpClusterAutoscalerResponse) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{19}
}

type DestroyClusterAutoscalerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectName string           `protobuf:"bytes,1,opt,name=projectName,proto3" json:"projectName,omitempty"`
	Cluster     *spec.K8Scluster `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
}

func (x *DestroyClusterAutoscalerRequest) Reset() {
	*x = DestroyClusterAutoscalerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyClusterAutoscalerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyClusterAutoscalerRequest) ProtoMessage() {}

func (x *DestroyClusterAutoscalerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyClusterAutoscalerRequest.ProtoReflect.Descriptor instead.
func (*DestroyClusterAutoscalerRequest) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{20}
}

func (x *DestroyClusterAutoscalerRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *DestroyClusterAutoscalerRequest) GetCluster() *spec.K8Scluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type DestroyClusterAutoscalerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DestroyClusterAutoscalerResponse) Reset() {
	*x = DestroyClusterAutoscalerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyClusterAutoscalerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyClusterAutoscalerResponse) ProtoMessage() {}

func (x *DestroyClusterAutoscalerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyClusterAutoscalerResponse.ProtoReflect.Descriptor instead.
func (*DestroyClusterAutoscalerResponse) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{21}
}

type PatchClusterInfoConfigMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DesiredCluster *spec.K8Scluster `protobuf:"bytes,1,opt,name=desiredCluster,proto3" json:"desiredCluster,omitempty"`
}

func (x *PatchClusterInfoConfigMapRequest) Reset() {
	*x = PatchClusterInfoConfigMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchClusterInfoConfigMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchClusterInfoConfigMapRequest) ProtoMessage() {}

func (x *PatchClusterInfoConfigMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchClusterInfoConfigMapRequest.ProtoReflect.Descriptor instead.
func (*PatchClusterInfoConfigMapRequest) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{22}
}

func (x *PatchClusterInfoConfigMapRequest) GetDesiredCluster() *spec.K8Scluster {
	if x != nil {
		return x.DesiredCluster
	}
	return nil
}

type PatchClusterInfoConfigMapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PatchClusterInfoConfigMapResponse) Reset() {
	*x = PatchClusterInfoConfigMapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchClusterInfoConfigMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchClusterInfoConfigMapResponse) ProtoMessage() {}

func (x *PatchClusterInfoConfigMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchClusterInfoConfigMapResponse.ProtoReflect.Descriptor instead.
func (*PatchClusterInfoConfigMapResponse) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{23}
}

type CiliumRolloutRestartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cluster *spec.K8Scluster `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
}

func (x *CiliumRolloutRestartRequest) Reset() {
	*x = CiliumRolloutRestartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CiliumRolloutRestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CiliumRolloutRestartRequest) ProtoMessage() {}

func (x *CiliumRolloutRestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CiliumRolloutRestartRequest.ProtoReflect.Descriptor instead.
func (*CiliumRolloutRestartRequest) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{24}
}

func (x *CiliumRolloutRestartRequest) GetCluster() *spec.K8Scluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type CiliumRolloutRestartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CiliumRolloutRestartResponse) Reset() {
	*x = CiliumRolloutRestartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CiliumRolloutRestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CiliumRolloutRestartResponse) ProtoMessage() {}

func (x *CiliumRolloutRestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CiliumRolloutRestartResponse.ProtoReflect.Descriptor instead.
func (*CiliumRolloutRestartResponse) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{25}
}

type PatchKubeProxyConfigMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DesiredCluster *spec.K8Scluster `protobuf:"bytes,1,opt,name=desiredCluster,proto3" json:"desiredCluster,omitempty"`
}

func (x *PatchKubeProxyConfigMapRequest) Reset() {
	*x = PatchKubeProxyConfigMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchKubeProxyConfigMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchKubeProxyConfigMapRequest) ProtoMessage() {}

func (x *PatchKubeProxyConfigMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchKubeProxyConfigMapRequest.ProtoReflect.Descriptor instead.
func (*PatchKubeProxyConfigMapRequest) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{26}
}

func (x *PatchKubeProxyConfigMapRequest) GetDesiredCluster() *spec.K8Scluster {
	if x != nil {
		return x.DesiredCluster
	}
	return nil
}

type PatchKubeProxyConfigMapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PatchKubeProxyConfigMapResponse) Reset() {
	*x = PatchKubeProxyConfigMapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuber_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchKubeProxyConfigMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchKubeProxyConfigMapResponse) ProtoMessage() {}

func (x *PatchKubeProxyConfigMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuber_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchKubeProxyConfigMapResponse.ProtoReflect.Descriptor instead.
func (*PatchKubeProxyConfigMapResponse) Descriptor() ([]byte, []int) {
	return file_kuber_proto_rawDescGZIP(), []int{27}
}

var File_kuber_proto protoreflect.FileDescriptor

var file_kuber_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63,
	0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x1a, 0x13, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x6d, 0x61, 0x6e,
	0x69, 0x66, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x13, 0x53,
	0x65, 0x74, 0x55, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x38, 0x0a, 0x0e, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x70, 0x65,
	0x63, 0x2e, 0x4b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x0e, 0x64, 0x65,
	0x73, 0x69, 0x72, 0x65, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0x50, 0x0a, 0x14,
	0x53, 0x65, 0x74, 0x55, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0e, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73,
	0x70, 0x65, 0x63, 0x2e, 0x4b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x0e,
	0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0x66,
	0x0a, 0x16, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4b, 0x75, 0x62, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x70, 0x65, 0x63,
	0x2e, 0x4b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x07, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4b,
	0x75, 0x62, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x45, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x75, 0x62, 0x65, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x73, 0x70, 0x65, 0x63, 0x2e, 0x4b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0x1a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4b, 0x75, 0x62, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73,
	0x70, 0x65, 0x63, 0x2e, 0x4b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x07,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b,
	0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x41, 0x0a, 0x13, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4b, 0x38, 0x73, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0xa2,
	0x01, 0x0a, 0x1b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a,
	0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x0d,
	0x6c, 0x6f, 0x61, 0x64, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4c, 0x42, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x0d, 0x6c, 0x6f, 0x61, 0x64, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x72, 0x73, 0x22, 0x1e, 0x0a, 0x1c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x8d, 0x01, 0x0a, 0x1a, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4c, 0x42, 0x53,
	0x63, 0x72, 0x61, 0x70, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4b, 0x38, 0x73, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x43,
	0x0a, 0x14, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x4c, 0x6f, 0x61, 0x64, 0x62, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73,
	0x70, 0x65, 0x63, 0x2e, 0x4c, 0x42, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x14, 0x64,
	0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x4c, 0x6f, 0x61, 0x64, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x72, 0x73, 0x22, 0x1d, 0x0a, 0x1b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4c, 0x42, 0x53, 0x63,
	0x72, 0x61, 0x70, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x49, 0x0a, 0x1b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4c, 0x42, 0x53, 0x63,
	0x72, 0x61, 0x70, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2a, 0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4b, 0x38, 0x73, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0x1e, 0x0a,
	0x1c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4c, 0x42, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4a, 0x0a,
	0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a,
	0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0x1f, 0x0a, 0x1d, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3f, 0x0a, 0x11, 0x50, 0x61,
	0x74, 0x63, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2a, 0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0x14, 0x0a, 0x12, 0x50,
	0x61, 0x74, 0x63, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x6d, 0x0a, 0x1d, 0x53, 0x65, 0x74, 0x55, 0x70, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x41, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4b, 0x38, 0x73,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x22, 0x20, 0x0a, 0x1e, 0x53, 0x65, 0x74, 0x55, 0x70, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x41, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x6f, 0x0a, 0x1f, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x41, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e,
	0x4b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x07, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x22, 0x22, 0x0a, 0x20, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x43, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x41, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5c, 0x0a, 0x20, 0x50, 0x61, 0x74, 0x63, 0x68,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0e, 0x64,
	0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4b, 0x38, 0x73, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x0e, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x43, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0x23, 0x0a, 0x21, 0x50, 0x61, 0x74, 0x63, 0x68, 0x43, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d,
	0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x49, 0x0a, 0x1b, 0x43, 0x69,
	0x6c, 0x69, 0x75, 0x6d, 0x52, 0x6f, 0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x70, 0x65,
	0x63, 0x2e, 0x4b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x07, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0x1e, 0x0a, 0x1c, 0x43, 0x69, 0x6c, 0x69, 0x75, 0x6d, 0x52,
	0x6f, 0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5a, 0x0a, 0x1e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x4b, 0x75,
	0x62, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0e, 0x64, 0x65, 0x73, 0x69, 0x72,
	0x65, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x0e, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x22, 0x21, 0x0a, 0x1f, 0x50, 0x61, 0x74, 0x63, 0x68, 0x4b, 0x75, 0x62, 0x65, 0x50, 0x72,
	0x6f, 0x78, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xd2, 0x0a, 0x0a, 0x0c, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x63, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4c,
	0x42, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x24, 0x2e,
	0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4c, 0x42,
	0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x4c, 0x42, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x13, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x4c, 0x42, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x23, 0x2e, 0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x4c, 0x42, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65,
	0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4c, 0x42, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x14,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x24, 0x2e, 0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x63, 0x6c, 0x61,
	0x75, 0x64, 0x69, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x66, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x25, 0x2e, 0x63, 0x6c, 0x61,
	0x75, 0x64, 0x69, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x26, 0x2e, 0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x53, 0x65, 0x74,
	0x55, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x2e, 0x63, 0x6c, 0x61, 0x75,
	0x64, 0x69, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6c, 0x61, 0x75, 0x64, 0x69,
	0x65, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4b,
	0x75, 0x62, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1f, 0x2e, 0x63, 0x6c, 0x61, 0x75,
	0x64, 0x69, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4b, 0x75, 0x62, 0x65, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x6c, 0x61,
	0x75, 0x64, 0x69, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4b, 0x75, 0x62, 0x65, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x10,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x75, 0x62, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x20, 0x2e, 0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4b, 0x75, 0x62, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4b, 0x75, 0x62, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x45, 0x0a, 0x0a, 0x50, 0x61, 0x74, 0x63, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1a, 0x2e,
	0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x4e, 0x6f, 0x64,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x6c, 0x61, 0x75,
	0x64, 0x69, 0x65, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x69, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x55, 0x70, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x41, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72,
	0x12, 0x26, 0x2e, 0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x70,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x41, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x63, 0x6c, 0x61, 0x75, 0x64,
	0x69, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x70, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x41,
	0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x6f, 0x0a, 0x18, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x41, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x12, 0x28, 0x2e,
	0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x41, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x63, 0x6c, 0x61, 0x75, 0x64, 0x69,
	0x65, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x41, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x72, 0x0a, 0x19, 0x50, 0x61, 0x74, 0x63, 0x68, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x12,
	0x29, 0x2e, 0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x63, 0x6c, 0x61,
	0x75, 0x64, 0x69, 0x65, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6c, 0x0a, 0x17, 0x50, 0x61, 0x74, 0x63, 0x68, 0x4b,
	0x75, 0x62, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61,
	0x70, 0x12, 0x27, 0x2e, 0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x50, 0x61, 0x74, 0x63,
	0x68, 0x4b, 0x75, 0x62, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x63, 0x6c, 0x61,
	0x75, 0x64, 0x69, 0x65, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x4b, 0x75, 0x62, 0x65, 0x50, 0x72,
	0x6f, 0x78, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x14, 0x43, 0x69, 0x6c, 0x69, 0x75, 0x6d, 0x52, 0x6f,
	0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x24, 0x2e, 0x63,
	0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x43, 0x69, 0x6c, 0x69, 0x75, 0x6d, 0x52, 0x6f, 0x6c,
	0x6c, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x63, 0x6c, 0x61, 0x75, 0x64, 0x69, 0x65, 0x2e, 0x43, 0x69, 0x6c,
	0x69, 0x75, 0x6d, 0x52, 0x6f, 0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kuber_proto_rawDescOnce sync.Once
	file_kuber_proto_rawDescData = file_kuber_proto_rawDesc
)

func file_kuber_proto_rawDescGZIP() []byte {
	file_kuber_proto_rawDescOnce.Do(func() {
		file_kuber_proto_rawDescData = protoimpl.X.CompressGZIP(file_kuber_proto_rawDescData)
	})
	return file_kuber_proto_rawDescData
}

var file_kuber_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_kuber_proto_goTypes = []interface{}{
	(*SetUpStorageRequest)(nil),               // 0: claudie.SetUpStorageRequest
	(*SetUpStorageResponse)(nil),              // 1: claudie.SetUpStorageResponse
	(*StoreKubeconfigRequest)(nil),            // 2: claudie.StoreKubeconfigRequest
	(*StoreKubeconfigResponse)(nil),           // 3: claudie.StoreKubeconfigResponse
	(*DeleteKubeconfigRequest)(nil),           // 4: claudie.DeleteKubeconfigRequest
	(*DeleteKubeconfigResponse)(nil),          // 5: claudie.DeleteKubeconfigResponse
	(*DeleteNodesRequest)(nil),                // 6: claudie.DeleteNodesRequest
	(*DeleteNodesResponse)(nil),               // 7: claudie.DeleteNodesResponse
	(*StoreClusterMetadataRequest)(nil),       // 8: claudie.StoreClusterMetadataRequest
	(*StoreClusterMetadataResponse)(nil),      // 9: claudie.StoreClusterMetadataResponse
	(*StoreLBScrapeConfigRequest)(nil),        // 10: claudie.StoreLBScrapeConfigRequest
	(*StoreLBScrapeConfigResponse)(nil),       // 11: claudie.StoreLBScrapeConfigResponse
	(*RemoveLBScrapeConfigRequest)(nil),       // 12: claudie.RemoveLBScrapeConfigRequest
	(*RemoveLBScrapeConfigResponse)(nil),      // 13: claudie.RemoveLBScrapeConfigResponse
	(*DeleteClusterMetadataRequest)(nil),      // 14: claudie.DeleteClusterMetadataRequest
	(*DeleteClusterMetadataResponse)(nil),     // 15: claudie.DeleteClusterMetadataResponse
	(*PatchNodesRequest)(nil),                 // 16: claudie.PatchNodesRequest
	(*PatchNodesResponse)(nil),                // 17: claudie.PatchNodesResponse
	(*SetUpClusterAutoscalerRequest)(nil),     // 18: claudie.SetUpClusterAutoscalerRequest
	(*SetUpClusterAutoscalerResponse)(nil),    // 19: claudie.SetUpClusterAutoscalerResponse
	(*DestroyClusterAutoscalerRequest)(nil),   // 20: claudie.DestroyClusterAutoscalerRequest
	(*DestroyClusterAutoscalerResponse)(nil),  // 21: claudie.DestroyClusterAutoscalerResponse
	(*PatchClusterInfoConfigMapRequest)(nil),  // 22: claudie.PatchClusterInfoConfigMapRequest
	(*PatchClusterInfoConfigMapResponse)(nil), // 23: claudie.PatchClusterInfoConfigMapResponse
	(*CiliumRolloutRestartRequest)(nil),       // 24: claudie.CiliumRolloutRestartRequest
	(*CiliumRolloutRestartResponse)(nil),      // 25: claudie.CiliumRolloutRestartResponse
	(*PatchKubeProxyConfigMapRequest)(nil),    // 26: claudie.PatchKubeProxyConfigMapRequest
	(*PatchKubeProxyConfigMapResponse)(nil),   // 27: claudie.PatchKubeProxyConfigMapResponse
	(*spec.K8Scluster)(nil),                   // 28: spec.K8scluster
	(*spec.LBcluster)(nil),                    // 29: spec.LBcluster
}
var file_kuber_proto_depIdxs = []int32{
	28, // 0: claudie.SetUpStorageRequest.desiredCluster:type_name -> spec.K8scluster
	28, // 1: claudie.SetUpStorageResponse.desiredCluster:type_name -> spec.K8scluster
	28, // 2: claudie.StoreKubeconfigRequest.cluster:type_name -> spec.K8scluster
	28, // 3: claudie.DeleteKubeconfigRequest.cluster:type_name -> spec.K8scluster
	28, // 4: claudie.DeleteNodesRequest.cluster:type_name -> spec.K8scluster
	28, // 5: claudie.DeleteNodesResponse.cluster:type_name -> spec.K8scluster
	28, // 6: claudie.StoreClusterMetadataRequest.cluster:type_name -> spec.K8scluster
	29, // 7: claudie.StoreClusterMetadataRequest.loadbalancers:type_name -> spec.LBcluster
	28, // 8: claudie.StoreLBScrapeConfigRequest.cluster:type_name -> spec.K8scluster
	29, // 9: claudie.StoreLBScrapeConfigRequest.desiredLoadbalancers:type_name -> spec.LBcluster
	28, // 10: claudie.RemoveLBScrapeConfigRequest.cluster:type_name -> spec.K8scluster
	28, // 11: claudie.DeleteClusterMetadataRequest.cluster:type_name -> spec.K8scluster
	28, // 12: claudie.PatchNodesRequest.cluster:type_name -> spec.K8scluster
	28, // 13: claudie.SetUpClusterAutoscalerRequest.cluster:type_name -> spec.K8scluster
	28, // 14: claudie.DestroyClusterAutoscalerRequest.cluster:type_name -> spec.K8scluster
	28, // 15: claudie.PatchClusterInfoConfigMapRequest.desiredCluster:type_name -> spec.K8scluster
	28, // 16: claudie.CiliumRolloutRestartRequest.cluster:type_name -> spec.K8scluster
	28, // 17: claudie.PatchKubeProxyConfigMapRequest.desiredCluster:type_name -> spec.K8scluster
	12, // 18: claudie.KuberService.RemoveLBScrapeConfig:input_type -> claudie.RemoveLBScrapeConfigRequest
	10, // 19: claudie.KuberService.StoreLBScrapeConfig:input_type -> claudie.StoreLBScrapeConfigRequest
	8,  // 20: claudie.KuberService.StoreClusterMetadata:input_type -> claudie.StoreClusterMetadataRequest
	14, // 21: claudie.KuberService.DeleteClusterMetadata:input_type -> claudie.DeleteClusterMetadataRequest
	0,  // 22: claudie.KuberService.SetUpStorage:input_type -> claudie.SetUpStorageRequest
	2,  // 23: claudie.KuberService.StoreKubeconfig:input_type -> claudie.StoreKubeconfigRequest
	4,  // 24: claudie.KuberService.DeleteKubeconfig:input_type -> claudie.DeleteKubeconfigRequest
	6,  // 25: claudie.KuberService.DeleteNodes:input_type -> claudie.DeleteNodesRequest
	16, // 26: claudie.KuberService.PatchNodes:input_type -> claudie.PatchNodesRequest
	18, // 27: claudie.KuberService.SetUpClusterAutoscaler:input_type -> claudie.SetUpClusterAutoscalerRequest
	20, // 28: claudie.KuberService.DestroyClusterAutoscaler:input_type -> claudie.DestroyClusterAutoscalerRequest
	22, // 29: claudie.KuberService.PatchClusterInfoConfigMap:input_type -> claudie.PatchClusterInfoConfigMapRequest
	26, // 30: claudie.KuberService.PatchKubeProxyConfigMap:input_type -> claudie.PatchKubeProxyConfigMapRequest
	24, // 31: claudie.KuberService.CiliumRolloutRestart:input_type -> claudie.CiliumRolloutRestartRequest
	13, // 32: claudie.KuberService.RemoveLBScrapeConfig:output_type -> claudie.RemoveLBScrapeConfigResponse
	11, // 33: claudie.KuberService.StoreLBScrapeConfig:output_type -> claudie.StoreLBScrapeConfigResponse
	9,  // 34: claudie.KuberService.StoreClusterMetadata:output_type -> claudie.StoreClusterMetadataResponse
	15, // 35: claudie.KuberService.DeleteClusterMetadata:output_type -> claudie.DeleteClusterMetadataResponse
	1,  // 36: claudie.KuberService.SetUpStorage:output_type -> claudie.SetUpStorageResponse
	3,  // 37: claudie.KuberService.StoreKubeconfig:output_type -> claudie.StoreKubeconfigResponse
	5,  // 38: claudie.KuberService.DeleteKubeconfig:output_type -> claudie.DeleteKubeconfigResponse
	7,  // 39: claudie.KuberService.DeleteNodes:output_type -> claudie.DeleteNodesResponse
	17, // 40: claudie.KuberService.PatchNodes:output_type -> claudie.PatchNodesResponse
	19, // 41: claudie.KuberService.SetUpClusterAutoscaler:output_type -> claudie.SetUpClusterAutoscalerResponse
	21, // 42: claudie.KuberService.DestroyClusterAutoscaler:output_type -> claudie.DestroyClusterAutoscalerResponse
	23, // 43: claudie.KuberService.PatchClusterInfoConfigMap:output_type -> claudie.PatchClusterInfoConfigMapResponse
	27, // 44: claudie.KuberService.PatchKubeProxyConfigMap:output_type -> claudie.PatchKubeProxyConfigMapResponse
	25, // 45: claudie.KuberService.CiliumRolloutRestart:output_type -> claudie.CiliumRolloutRestartResponse
	32, // [32:46] is the sub-list for method output_type
	18, // [18:32] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_kuber_proto_init() }
func file_kuber_proto_init() {
	if File_kuber_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kuber_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUpStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUpStorageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreKubeconfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreKubeconfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKubeconfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKubeconfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNodesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNodesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreClusterMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreClusterMetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreLBScrapeConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreLBScrapeConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveLBScrapeConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveLBScrapeConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteClusterMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteClusterMetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchNodesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchNodesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUpClusterAutoscalerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUpClusterAutoscalerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyClusterAutoscalerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyClusterAutoscalerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchClusterInfoConfigMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchClusterInfoConfigMapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CiliumRolloutRestartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CiliumRolloutRestartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchKubeProxyConfigMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuber_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchKubeProxyConfigMapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kuber_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kuber_proto_goTypes,
		DependencyIndexes: file_kuber_proto_depIdxs,
		MessageInfos:      file_kuber_proto_msgTypes,
	}.Build()
	File_kuber_proto = out.File
	file_kuber_proto_rawDesc = nil
	file_kuber_proto_goTypes = nil
	file_kuber_proto_depIdxs = nil
}
