// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.5
// source: kubeEleven.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KubeElevenService_BuildCluster_FullMethodName   = "/claudie.KubeElevenService/BuildCluster"
	KubeElevenService_DestroyCluster_FullMethodName = "/claudie.KubeElevenService/DestroyCluster"
)

// KubeElevenServiceClient is the client API for KubeElevenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KubeElevenServiceClient interface {
	// BuildCluster builds the kubernetes clusters specified in the provided config.
	BuildCluster(ctx context.Context, in *BuildClusterRequest, opts ...grpc.CallOption) (*BuildClusterResponse, error)
	// DestroyCluster destroys the kubernetes clusters specified in the provided config.
	DestroyCluster(ctx context.Context, in *DestroyClusterRequest, opts ...grpc.CallOption) (*DestroyClusterResponse, error)
}

type kubeElevenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKubeElevenServiceClient(cc grpc.ClientConnInterface) KubeElevenServiceClient {
	return &kubeElevenServiceClient{cc}
}

func (c *kubeElevenServiceClient) BuildCluster(ctx context.Context, in *BuildClusterRequest, opts ...grpc.CallOption) (*BuildClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildClusterResponse)
	err := c.cc.Invoke(ctx, KubeElevenService_BuildCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeElevenServiceClient) DestroyCluster(ctx context.Context, in *DestroyClusterRequest, opts ...grpc.CallOption) (*DestroyClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyClusterResponse)
	err := c.cc.Invoke(ctx, KubeElevenService_DestroyCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KubeElevenServiceServer is the server API for KubeElevenService service.
// All implementations must embed UnimplementedKubeElevenServiceServer
// for forward compatibility.
type KubeElevenServiceServer interface {
	// BuildCluster builds the kubernetes clusters specified in the provided config.
	BuildCluster(context.Context, *BuildClusterRequest) (*BuildClusterResponse, error)
	// DestroyCluster destroys the kubernetes clusters specified in the provided config.
	DestroyCluster(context.Context, *DestroyClusterRequest) (*DestroyClusterResponse, error)
	mustEmbedUnimplementedKubeElevenServiceServer()
}

// UnimplementedKubeElevenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKubeElevenServiceServer struct{}

func (UnimplementedKubeElevenServiceServer) BuildCluster(context.Context, *BuildClusterRequest) (*BuildClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildCluster not implemented")
}
func (UnimplementedKubeElevenServiceServer) DestroyCluster(context.Context, *DestroyClusterRequest) (*DestroyClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyCluster not implemented")
}
func (UnimplementedKubeElevenServiceServer) mustEmbedUnimplementedKubeElevenServiceServer() {}
func (UnimplementedKubeElevenServiceServer) testEmbeddedByValue()                           {}

// UnsafeKubeElevenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KubeElevenServiceServer will
// result in compilation errors.
type UnsafeKubeElevenServiceServer interface {
	mustEmbedUnimplementedKubeElevenServiceServer()
}

func RegisterKubeElevenServiceServer(s grpc.ServiceRegistrar, srv KubeElevenServiceServer) {
	// If the following call pancis, it indicates UnimplementedKubeElevenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KubeElevenService_ServiceDesc, srv)
}

func _KubeElevenService_BuildCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeElevenServiceServer).BuildCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeElevenService_BuildCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeElevenServiceServer).BuildCluster(ctx, req.(*BuildClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeElevenService_DestroyCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeElevenServiceServer).DestroyCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeElevenService_DestroyCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeElevenServiceServer).DestroyCluster(ctx, req.(*DestroyClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KubeElevenService_ServiceDesc is the grpc.ServiceDesc for KubeElevenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KubeElevenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "claudie.KubeElevenService",
	HandlerType: (*KubeElevenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuildCluster",
			Handler:    _KubeElevenService_BuildCluster_Handler,
		},
		{
			MethodName: "DestroyCluster",
			Handler:    _KubeElevenService_DestroyCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kubeEleven.proto",
}
