apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: test-set4
spec:
  providers:
    - name: oci-1
      providerType: oci
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.12
        path: "templates/terraformer/oci"
      secretRef:
        name: oci-secret
        namespace: e2e-secrets
    - name: cloudflare-1
      providerType: cloudflare
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.12
        path: "templates/terraformer/cloudflare"
      secretRef:
        name: cloudflare-secret
        namespace: e2e-secrets
    - name: gcp-1
      providerType: gcp
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.12
        path: "templates/terraformer/gcp"
      secretRef:
        name: gcp-secret
        namespace: e2e-secrets
  nodePools:
    dynamic:
      - name: oci-kube-nodes
        providerSpec:
          name: oci-1
          region: eu-frankfurt-1
          zone: hsVQ:EU-FRANKFURT-1-AD-1
        count: 1
        serverType: VM.Standard1.1
        # https://docs.oracle.com/en-us/iaas/images/ubuntu-2404/canonical-ubuntu-24-04-2024-08-28-0.htm
        image: ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa7hxwyz4qiasffo7n7s4ep5lywpzwgkc2am65frqrqinoyitmxxla
        storageDiskSize: 50

      - name: gcp-kube-nodes
        providerSpec:
          name: gcp-1
          region: europe-west2
          zone: europe-west2-c
        count: 1
        serverType: e2-medium
        image: ubuntu-2404-noble-amd64-v20250313
        storageDiskSize: 50

      #-----------LB nodepools----------
      - name: gcp-ldbl-nodes
        providerSpec:
          name: gcp-1
          region: europe-west1
          zone: europe-west1-c
        count: 1
        serverType: e2-small
        image: ubuntu-2404-noble-amd64-v20250313
        storageDiskSize: 50
  kubernetes:
    clusters:
      - name: ts4-c-1-cluster-test-set-no4
        version: 1.30.0
        network: 192.168.2.0/24
        installationProxy:
          mode: "on"
        pools:
          control:
            - gcp-kube-nodes
          compute:
            - oci-kube-nodes
            - gcp-kube-nodes
  loadBalancers:
    roles:
      - name: apiserver-lb
        protocol: tcp
        port: 6443
        targetPort: 6443
        targetPools:
          - gcp-kube-nodes
    clusters:
      - name: ts4-lb1-cluster-test-set-no4
        roles:
          - apiserver-lb
        dns:
          dnsZone: claudie.dev
          provider: cloudflare-1
        targetedK8s: ts4-c-1-cluster-test-set-no4
        pools:
          - gcp-ldbl-nodes
