apiVersion: claudie.io/v1beta1
kind: InputManifest
metadata:
  name: test-set5
spec:
  providers:
    - name: aws-1
      providerType: aws
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.8
        path: "templates/terraformer/aws"
      secretRef:
        name: aws-secret
        namespace: e2e-secrets
    - name: cloudflare-1
      providerType: cloudflare
      templates:
        repository: "https://github.com/berops/claudie-config"
        tag: v0.9.8
        path: "templates/terraformer/cloudflare"
      secretRef:
        name: cloudflare-secret
        namespace: e2e-secrets

  nodePools:
    dynamic:
      - name: aws-ctrl-nodes
        providerSpec:
          name: aws-1
          region: eu-central-1
          zone: eu-central-1c
        count: 1
        serverType: t3.small
        #ubuntu
        image: ami-0084a47cc718c111a
        storageDiskSize: 50

      - name: aws-ldbl-nodes
        providerSpec:
          name: aws-1
          region: eu-central-1
          zone: eu-central-1c
        count: 1
        serverType: t3.small
        #ubuntu
        image: ami-0084a47cc718c111a
        storageDiskSize: 50

    static:
      - name: static-pool-02
        nodes:
          - endpoint: replace-me
            secretRef:
              name: static-nodes-key
              namespace: e2e-secrets
          - endpoint: replace-me
            secretRef:
              name: static-nodes-key
              namespace: e2e-secrets

  kubernetes:
    clusters:
      - name: hybrid-cluster-test-set-no-5
        version: v1.30.0
        network: 192.168.2.0/24
        pools:
          control:
            - aws-ctrl-nodes
          compute:
            - static-pool-02

  loadBalancers:
    roles:
      - name: apiserver-lb
        protocol: tcp
        port: 6443
        targetPort: 6443
        targetPools:
          - aws-ctrl-nodes
    clusters:
      - name: hybrid-cluster-lb-test-set-5
        roles:
          - apiserver-lb
        dns:
          dnsZone: claudie.dev
          provider: cloudflare-1
        targetedK8s: hybrid-cluster-test-set-no-5
        pools:
          - aws-ldbl-nodes
